name: nginx-slim-docker-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push to Docker Hub
      run: |
           echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
           sh build.sh
           echo "Docker publish completed"
    - name: Push New Version to File
      run: |
           echo -e `git config --global user.name 'github-ci' && git config --global user.email 'github-ci@users.noreply.github.com' && git add LATEST_RELEASE && git commit -am "New Docker Version" && git push`
    - name: Github Docker Package
      run: |
            echo ${{ secrets.GH_TOKEN }} | docker login docker.pkg.github.com -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            sh github-package.sh
            echo "Package publish completed"
#    - name: Change log
#      run: git log -1 --oneline --pretty='%an %ai, %s' > git-log.txt
#    - name: Create Release
#      id: create_release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#      with:
#        tag_name: ${{ github.ref }}
#        release_name: Release ${{ github.ref }}
#        body_path: git-log.txt
#        draft: false
#        prerelease: false