name: Nginx Slim Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push to Docker Hub
      run: |
           echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
           sh build.sh
    - name: Push New Version to File
      run: |
           git config --global user.name 'github-ci'
           git config --global user.email 'github-ci@users.noreply.github.com'
           git commit -am "New Docker Version"
           git push
    - name: Github Docker Package
      run: |
            echo ${{ secrets.GH_TOKEN }} | docker login docker.pkg.github.com -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            sh github-package.sh